### ISSUE TITLE
associate points with contributor name and commit count

### ISSUE THREAD

**Issue by michaelficarra** [jakub-/github-contributors-geojson#2]

**Comment by jakub-** [comment]
This would be easy to do (GitHub already gives you the commit count for contributors) but I am rather skeptical about the rationale. I don't really want this to be a competition as such, rather just a way to show case that contributors come from different places. But of course the script can be modified to support this so if it's an important use case for someone else, I'll accept a PR.

**Comment by michaelficarra** [comment]
I'm okay omitting commit count. I was just thinking it would be nice to click the point and see who lives in that remote location.
